#!/usr/bin/env bash
#
# Creates a double-clickable sync button.
#
#   ./scripts/install-button.sh              # -> ~/Desktop
#   ./scripts/install-button.sh ~/Applications
#   ./scripts/install-button.sh --uninstall
#
# The result is a .command file. Double-clicking it opens Terminal, runs one
# sync, posts a macOS notification with the outcome, and closes itself when the
# run succeeded. On failure the window stays open with the error visible.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
NAME="캘린더 동기화.command"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
die() { printf '\033[31m✗  %s\033[0m\n' "$*" >&2; exit 1; }

if [ "${1:-}" = "--uninstall" ]; then
  removed=0
  for dir in "$HOME/Desktop" "$HOME/Applications" "$HOME"; do
    if [ -f "$dir/$NAME" ]; then rm -f "$dir/$NAME"; echo "Removed $dir/$NAME"; removed=1; fi
  done
  [ "$removed" = 1 ] || echo "Nothing to remove."
  exit 0
fi

DEST_DIR="${1:-$HOME/Desktop}"
[ -d "$DEST_DIR" ] || die "no such directory: $DEST_DIR"
[ -x .venv/bin/calhub ] || die "calhub is not installed in .venv. Run ./scripts/install-macos.sh first."
[ -f config.yaml ] || die "no config.yaml found. Run ./scripts/install-macos.sh first."

TARGET="$DEST_DIR/$NAME"

say "Writing $TARGET"
# The quoted heredoc keeps the button's own script intact; only ROOT is
# substituted afterwards, so a double-click works from anywhere.
cat > "$TARGET" <<'BUTTONEOF'
#!/bin/bash
# Generated by calhub scripts/install-button.sh -- safe to delete.

ROOT="__CALHUB_ROOT__"
cd "$ROOT" || { echo "프로젝트 폴더를 찾을 수 없습니다: $ROOT"; read -r; exit 1; }

# AppleScript string literals break on quotes and backslashes, and this text
# comes from command output, so strip both before interpolating.
notify() {
  local title="$1" message="$2"
  message="$(printf '%s' "$message" | tr -d '"\\' | tr '\n' ' ' | cut -c1-200)"
  osascript -e "display notification \"$message\" with title \"$title\"" >/dev/null 2>&1 || true
}

clear
echo "캘린더 동기화 중..."
echo "────────────────────────────────────────"

output="$("$ROOT/.venv/bin/calhub" sync 2>&1)"
status=$?

echo "$output"
echo "────────────────────────────────────────"

if [ $status -eq 0 ]; then
  summary="$(printf '%s' "$output" | grep -E 'applied:|written' | tail -1)"
  [ -n "$summary" ] || summary="변경 사항 없음"
  echo "완료. $summary"
  notify "캘린더 동기화 완료" "$summary"
  sleep 2
  # Ask Terminal to close this window. Harmless if it is not Terminal.
  osascript -e 'tell application "Terminal" to close (every window whose name contains "캘린더 동기화")' >/dev/null 2>&1 &
  exit 0
fi

echo "실패 (종료 코드 $status)."
echo "위 메시지를 확인하세요. 진단은 다음 명령으로:"
echo "    cd \"$ROOT\" && source .venv/bin/activate && calhub doctor"
notify "캘린더 동기화 실패" "터미널 창을 확인하세요"
echo
echo "Enter를 누르면 창이 닫힙니다."
read -r
exit $status
BUTTONEOF

# Bake in the absolute project path.
python3 - "$TARGET" "$ROOT" <<'PYEOF'
import pathlib, sys
path, root = pathlib.Path(sys.argv[1]), sys.argv[2]
path.write_text(path.read_text(encoding="utf-8").replace("__CALHUB_ROOT__", root), encoding="utf-8")
PYEOF

chmod +x "$TARGET"

cat <<EOF

버튼이 만들어졌습니다:
  $TARGET

사용법
  더블클릭하면 동기화가 1회 실행됩니다.
  성공하면 알림이 뜨고 창이 자동으로 닫힙니다.
  실패하면 창이 열린 채로 남아 오류를 보여줍니다.

Dock에 두려면
  Finder에서 이 파일을 Dock의 오른쪽(휴지통 쪽) 구역으로 끌어다 놓습니다.

아이콘을 바꾸려면
  파일 선택 -> ⌘I -> 왼쪽 위 아이콘 클릭 -> 원하는 이미지 붙여넣기(⌘V)

제거
  ./scripts/install-button.sh --uninstall
EOF
